using System;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;

namespace LaborExchange.Client.Helpers
{
    /// <summary>
    /// Позволяет использовать атрибуты Brosable и DisplayName на DataGrid
    /// </summary>
    public static class DataGridGenerateColumnBehavior
    {
        public static readonly DependencyProperty UseBrowsableAttributeOnColumnProperty =
            DependencyProperty.RegisterAttached("UseBrowsableAttributeOnColumn",
            typeof(bool),
            typeof(DataGridGenerateColumnBehavior),
            new UIPropertyMetadata(false, UseBrowsableAttributeOnColumnChanged));

        public static readonly DependencyProperty StretchLastColumnProperty =
            DependencyProperty.RegisterAttached("StretchLastColumn",
                typeof(bool),
                typeof(DataGridGenerateColumnBehavior),
                new UIPropertyMetadata(false, StretchLastColumnChanged));


        public static bool GetUseBrowsableAttributeOnColumn(DependencyObject obj)
        {
            return (bool)obj.GetValue(UseBrowsableAttributeOnColumnProperty);
        }

        public static void SetUseBrowsableAttributeOnColumn(DependencyObject obj, bool val)
        {
            obj.SetValue(UseBrowsableAttributeOnColumnProperty, val);
        }

        public static void SetStretchLastColumn(DependencyObject element, bool value)
        {
            element.SetValue(StretchLastColumnProperty, value);
        }

        public static bool GetStretchLastColumn(DependencyObject element)
        {
            return (bool)element.GetValue(StretchLastColumnProperty);
        }


        private static void UseBrowsableAttributeOnColumnChanged(DependencyObject obj, DependencyPropertyChangedEventArgs e)
        {
            var dataGrid = obj as DataGrid;
            if (dataGrid != null)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.AutoGeneratingColumn += DataGridOnAutoGeneratingColumn;
                }
                else
                {
                    dataGrid.AutoGeneratingColumn -= DataGridOnAutoGeneratingColumn;
                }
            }
        }

        private static void StretchLastColumnChanged(DependencyObject obj, DependencyPropertyChangedEventArgs e)
        {
            var dataGrid = obj as DataGrid;
            if (dataGrid != null)
            {
                if ((bool)e.NewValue)
                {
                    dataGrid.AutoGeneratedColumns += DataGridOnAutoGeneratedColumns;
                }
                else
                {
                    dataGrid.AutoGeneratedColumns -= DataGridOnAutoGeneratedColumns;
                }
            }
        }

        private static void DataGridOnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var propDesc = e.PropertyDescriptor as PropertyDescriptor;

            if (propDesc != null)
            {
                foreach (Attribute att in propDesc.Attributes)
                {
                    var browsableAttribute = att as BrowsableAttribute;
                    if (browsableAttribute != null)
                    {
                        if (!browsableAttribute.Browsable)
                        {
                            e.Cancel = true;
                        }
                    }

                    var displayName = att as DisplayNameAttribute;
                    if (displayName != null)
                    {
                        e.Column.Header = displayName.DisplayName;
                    }
                }
            }
        }

        private static void DataGridOnAutoGeneratedColumns(object sender, EventArgs e)
        {
            ((DataGrid) sender).Columns.Last().Width = new DataGridLength(1, DataGridLengthUnitType.Star);
        }
    }
}